name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: debug-test
            build_dir: debug
          - preset: release-test
            build_dir: release
    name: ${{ matrix.preset }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Run binary (terminates on EOF)
        run: ./build/${{ matrix.build_dir }}/xq </dev/null

      - name: Test
        run: ctest --preset ${{ matrix.preset }}
